// Generate config.yaml + .env from a plain data structure.
//
// data shape:
// {
//   server:   { host, port, auth: bool, apiKey: string },
//   defaults: { timeout, rerouteTimeout, cooldown },   // e.g. "120s"
//   credentials: [
//     { name, kind: 'openai'|'azure'|'local', baseUrl?, endpoint?, apiVersion?, key },
//   ],
//   models: [
//     { name, domain, mode, timeout?, rerouteTimeout?, cooldown?,
//       backends: [{ credential, model }] },
//   ],
// }
//
// Secrets are written to .env only; config.yaml references ${VAR} names.
'use strict';

const fs = require('node:fs');
const path = require('node:path');

// envName(credentialName) -> e.g. "openai-main" -> "LLMR_OPENAI_MAIN"
function envName(name) {
  return 'LLMR_' + String(name).toUpperCase().replace(/[^A-Z0-9]+/g, '_').replace(/^_+|_+$/g, '');
}

function yamlStr(s) {
  // Quote strings that could be misread as numbers/booleans or contain ':'.
  if (/^[A-Za-z_][A-Za-z0-9_-]*$/.test(s) && !/^(true|false|null|yes|no|on|off)$/i.test(s)) return s;
  return JSON.stringify(s);
}

function buildYaml(data) {
  const L = [];
  L.push('# llm-router configuration — generated by `npx chinchilla-llm-router init`.');
  L.push('# Secrets live in ./.env (never in this file); ${VAR} refs are expanded at startup.');
  L.push('');
  L.push('server:');
  L.push(`  host: ${yamlStr(data.server.host)}`);
  L.push(`  port: ${data.server.port}`);
  if (data.server.auth) {
    L.push('  api_key: ${ROUTER_API_KEY}');
  } else {
    L.push('  # api_key: ${ROUTER_API_KEY}   # uncomment to require Bearer auth');
  }
  L.push('');
  L.push('defaults:');
  L.push(`  timeout: ${data.defaults.timeout}`);
  L.push(`  reroute_timeout: ${data.defaults.rerouteTimeout}`);
  L.push(`  cooldown: ${data.defaults.cooldown}`);
  L.push('');
  L.push('credentials:');
  for (const cred of data.credentials) {
    const env = envName(cred.name);
    L.push(`  ${yamlStr(cred.name)}:`);
    L.push(`    type: ${cred.kind === 'azure' ? 'azure' : 'openai'}`);
    if (cred.kind === 'azure') {
      L.push(`    endpoint: \${${env}_ENDPOINT}`);
      L.push(`    api_key: \${${env}_KEY}`);
      if (cred.apiVersion) L.push(`    api_version: "${cred.apiVersion}"`);
    } else {
      L.push(`    api_key: \${${env}_KEY}`);
      if (cred.baseUrl && cred.baseUrl !== 'https://api.openai.com/v1') {
        L.push(`    base_url: \${${env}_BASE_URL}`);
      }
    }
  }
  L.push('');
  L.push('models:');
  for (const m of data.models) {
    L.push(`  - name: ${yamlStr(m.name)}`);
    L.push(`    domain: ${yamlStr(m.domain)}`);
    L.push(`    mode: ${m.mode}`);
    if (m.timeout) L.push(`    timeout: ${m.timeout}`);
    if (m.rerouteTimeout) L.push(`    reroute_timeout: ${m.rerouteTimeout}`);
    if (m.cooldown) L.push(`    cooldown: ${m.cooldown}`);
    L.push('    backends:');
    for (const b of m.backends) {
      L.push(`      - credential: ${yamlStr(b.credential)}`);
      L.push(`        model: ${yamlStr(b.model)}`);
    }
  }
  L.push('');
  return L.join('\n');
}

function buildEnv(data) {
  const L = [];
  L.push('# llm-router environment — generated by `npx chinchilla-llm-router init`.');
  L.push('# Loaded by the router at startup from the working directory (./.env).');
  L.push('# Keep this file private (chmod 600). Never commit it.');
  L.push('');
  if (data.server.auth) {
    L.push('# Client auth: clients must send "Authorization: Bearer <ROUTER_API_KEY>"');
    L.push(`ROUTER_API_KEY=${data.server.apiKey}`);
    L.push('');
  }
  for (const cred of data.credentials) {
    const env = envName(cred.name);
    L.push(`# credential "${cred.name}" (${cred.kind})`);
    if (cred.kind === 'azure') {
      L.push(`${env}_ENDPOINT=${cred.endpoint}`);
    } else if (cred.baseUrl && cred.baseUrl !== 'https://api.openai.com/v1') {
      L.push(`${env}_BASE_URL=${cred.baseUrl}`);
    }
    L.push(`${env}_KEY=${cred.key}`);
    L.push('');
  }
  return L.join('\n');
}

// writeConfig(p, data) — writes config.yaml and .env (chmod 600).
function writeConfig(p, data) {
  fs.mkdirSync(p.root, { recursive: true });
  fs.writeFileSync(p.config, buildYaml(data), { mode: 0o644 });
  fs.writeFileSync(p.env, buildEnv(data), { mode: 0o600 });
  return { config: p.config, env: p.env };
}

// genApiKey() -> "sk-lr-<32 hex chars>"
function genApiKey() {
  const crypto = require('node:crypto');
  return 'sk-lr-' + crypto.randomBytes(16).toString('hex');
}

module.exports = { buildYaml, buildEnv, writeConfig, envName, genApiKey };
